### PR TITLE
python3 support and some simple unit tests

### PR DESCRIPTION
**Pull request by klintan**
Some very simpel unittests to confirm libraries as working etc. Also updated some things that I needed for it to work on python3. It is not backwards compatible as of now (will probably be enough to include a import __future__ print (something like that)). 

Let me know what you think,

### CODE REVIEW

**Comment by shelhamer** [comment]
Hey, thanks for porting this to the future! Could you include whatever little fixes are needed to preserve backwards compatibility with Python 2.7? I'd be happy to merge after that.

**Comment by klintan** [comment]
I'll fix it and do a new commit :)

**Comment by klintan** [comment]
Finally updated this for backwards compatibility, changed to setuptools in setup.py and updated some things in the setup py to make sure the module installs correctly. The tests pass, but feel free to try it on python2.7. Let me know if there is anything else you want me to change.

**Comment by shelhamer** [comment]
Merging since this looks good to me at a glance, thanks @klintan !

**Pull request merged**
